/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package daw;

import controladores.UsuarioController;
import entidades.Disco;
import entidades.Usuario;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ignacio
 */
public class MostrarUsuarios extends javax.swing.JFrame {

    private UsuarioController usuarioController = new UsuarioController();

    /**
     * Creates new form MostrarUsuarios
     */
    public MostrarUsuarios() {
        setLocationRelativeTo(null);
        setResizable(false);
        initComponents();
        cargarUsuariosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CrearUsuario = new javax.swing.JButton();
        BorrarUsuario = new javax.swing.JButton();
        ActualizarUsuario = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        TextoTitulo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 720, 460));

        CrearUsuario.setBackground(new java.awt.Color(255, 255, 255));
        CrearUsuario.setForeground(new java.awt.Color(0, 0, 0));
        CrearUsuario.setText("Crear Usuario");
        CrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(CrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 190, 50));

        BorrarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        BorrarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        BorrarUsuario.setText("Borrar Usuario");
        BorrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(BorrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 240, 190, 50));

        ActualizarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        ActualizarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        ActualizarUsuario.setText("Actualizar Usuario");
        getContentPane().add(ActualizarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, 190, 50));

        Volver.setBackground(new java.awt.Color(255, 255, 255));
        Volver.setForeground(new java.awt.Color(0, 0, 0));
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 190, 50));

        TextoTitulo.setFont(new java.awt.Font("Fira Sans Condensed ExtraBold", 1, 24)); // NOI18N
        TextoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        TextoTitulo.setText("Listado de Usuarios");
        getContentPane().add(TextoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 250, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoVarios.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioActionPerformed
        CrearUsuario.addActionListener(e -> {
            try {
                String nombre = JOptionPane.showInputDialog(this, "Nombre del usuario:");
                String dni = JOptionPane.showInputDialog(this, "DNI del usuario:");
                String localidad = JOptionPane.showInputDialog(this, "Localidad del usuario:");
                String telefono = JOptionPane.showInputDialog(this, "Teléfono del usuario:");

                if (nombre == null || dni == null || localidad == null || telefono == null
                        || nombre.isEmpty() || dni.isEmpty() || localidad.isEmpty() || telefono.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
                    return;
                }

                Usuario nuevo = new Usuario();
                nuevo.setNombreUsuario(nombre);
                nuevo.setDniUsuario(dni);
                nuevo.setLocalidadUsuario(localidad);
                nuevo.setTelefUsuario(telefono);

                usuarioController.create(nuevo);
                cargarUsuariosEnTabla();
                JOptionPane.showMessageDialog(this, "Usuario creado correctamente.");
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al crear usuario.");
            }
        });
    }//GEN-LAST:event_CrearUsuarioActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        new Seleccion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void BorrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarUsuarioActionPerformed
        BorrarUsuario.addActionListener(e -> {
            int fila = jTable1.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(this, "Selecciona un usuario para borrar.");
                return;
            }

            int codUsuario = (int) jTable1.getValueAt(fila, 0);
            int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres borrar el usuario " + codUsuario + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                try {
                    usuarioController.delete(codUsuario);
                    cargarUsuariosEnTabla();
                    JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente.");
                } catch (HeadlessException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Error al eliminar usuario.");
                }
            }
        });

    }//GEN-LAST:event_BorrarUsuarioActionPerformed

    private void cargarUsuariosEnTabla() {
        List<Usuario> usuario = usuarioController.findAll();

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"ID", "Nombre", "DNI", "Localidad", "Telefono", "Coleccion de Ventas"});

        for (Usuario u : usuario) {
            modelo.addRow(new Object[]{
                u.getCodUsuario(),
                u.getNombreUsuario(),
                u.getDniUsuario(),
                u.getLocalidadUsuario(),
                u.getTelefUsuario(),
                (u.getVentaCollection() != null) ? u.getVentaCollection() : "Sin ventas"
            });
        }

        jTable1.setModel(modelo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarUsuario;
    private javax.swing.JButton BorrarUsuario;
    private javax.swing.JButton CrearUsuario;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel TextoTitulo;
    private javax.swing.JButton Volver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
